server:
  port: 9094
spring:
  application:
    name: msvc-pagosonline
app:
  api:
    base-url: http://localhost:8080
eureka:
  instance:
    hostname: msvc-pagosonline  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Reemplazar localhost con el nombre del servicio Eureka en Docker Compose
