server:
  port: 9091
eureka:
  instance:
    hostname: msvc-login  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICEURL}:8761/eureka/  # Usar el nombre del servicio Docker
