server:
  port: 9095
eureka:
  instance:
    hostname: msvc-gestiondocumental  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Reemplazar localhost con el nombre del servicio Eureka en Docker Compose
