server:
  port: 9095
eureka:
  instance:
    hostname: msvc-gestiondocumental  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://192.168.0.69:8761/eureka  # Reemplazar 192.168.0.69 con el nombre del servicio Eureka en Docker Compose
