server:
  port: 9095

eureka:
  instance:
    hostname: msvc-gestiondocumental
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICEURL:http://msvc-eureka}:8761/eureka/
logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: America/Guayaquil

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_GD_URL:jdbc:postgresql://192.168.0.46:5432/GesDoc?currentSchema=public}
    username: ${DB_GD_USER:postgres}
    password: ${DB_GD_PASS:3pmapaT24}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  entity-code: ${ENTITY_CODE:EPMAPA-T}
  default-year: ${YEAR:2025}



