server:
  port: 9102
spring:
  application:
    name: msvc-contabilidad
eureka:
  instance:
    hostname: msvc-contabilidad
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICEURL:http://msvc-eureka}:8761/eureka/
