server:
  port: 9093
eureka:
  instance:
    hostname: msvc-comercializacion  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://192.168.0.70:8761/eureka  # Reemplazar localhost con el nombre del servicio Eureka en Docker Compose
