server:
  port: 9092
spring:
  application:
    name: msvc-recaudacion
eureka:
  instance:
    hostname: msvc-recaudacion  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://192.168.100.16:8761/eureka  # Reemplazar localhost con el nombre del servicio Eureka en Docker Compose
