server:
  port: 9097
spring:
  application:
    name: msvc-reportesjr
eureka:
  instance:
    hostname: msvc-reportesjr  # El nombre del contenedor o el servicio en Docker Compose
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # Usar el nombre del servicio Docker
