version: "3.9"
services:
  config-server:
    build:
      context: config
      dockerfile: Dockerfile
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - config-server

  msvc-eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    image: msvc-eureka:latest
    container_name: msvc-eureka
    ports:
      - "8761:8761"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-eureka
  msvc-gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    image: msvc-gateway:latest
    container_name: msvc-gateway
    ports:
      - "9090:9090"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-gateway:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-gateway
  msvc-login:
    build:
      context: login
      dockerfile: Dockerfile
    image: msvc-login:latest
    container_name: msvc-login
    ports:
      - "9091:9091"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-login:9091/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-login
  msvc-recaudacion:
    build:
      context: recaudacion
      dockerfile: Dockerfile
    image: msvc-recaudacion:latest
    container_name: msvc-recaudacion
    ports:
      - "9092:9092"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-recaudacion:9092/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-recaudacion
  msvc-comercializacion:
    build:
      context: comercializacion
      dockerfile: Dockerfile
    image: msvc-comercializacion:latest
    container_name: msvc-comercializacion
    ports:
      - "9093:9093"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-comercializacion:9093/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-comercializacion
  msvc-rrhh:
    build:
      context: rrhh
      dockerfile: Dockerfile
    image: msvc-rrhh:latest
    container_name: msvc-rrhh
    ports:
      - "9101:9101"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-rrhh:9101/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-rrhh
  msvc-contabilidad:
    build:
      context: contabilidad
      dockerfile: Dockerfile
    image: msvc-contabilidad:latest
    container_name: msvc-contabilidad
    ports:
      - "9102:9102"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-contabilidad:9102/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-contabilidad
  msvc-pagosonline:
    build:
      context: pagosonline
      dockerfile: Dockerfile
    image: msvc-pagosonline:latest
    container_name: msvc-pagosonline
    ports:
      - "32:32"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - PAGOSONLINE_API_BASE_URL=http://msvc-pagosonline:32
      - ERP_BACKEND_BASE_URL=http://192.168.0.165:8080/fec_facturaapi
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-pagosonline:32/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-pagosonline
  msvc-sri:
    build:
      context: sri-files
      dockerfile: Dockerfile
      network: host
    image: msvc-sri:latest
    container_name: msvc-sri
    ports:
      - "9096:9096"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-sri:9096/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-sri
  msvc-reportesjr:
    build:
      context: reportes-jr
      dockerfile: Dockerfile
    image: msvc-reportesjr:latest
    container_name: msvc-reportesjr
    ports:
      - "9097:9097"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-reportesjr:9097/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-reportesjr
  msvc-epmapaapi:
    build:
      context: epmapaapi
      dockerfile: Dockerfile
    image: msvc-epmapaapi:latest
    container_name: msvc-epmapaapi
    ports:
      - "9098:9098"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-epmapaapi:9098/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-epmapaapi
  msvc-emails:
    build:
      context: .
      dockerfile: emails/Dockerfile
    image: msvc-emails:latest
    container_name: msvc-emails
    ports:
      - "9099:9099"
    environment:
      - TZ=America/Guayaquil
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Guayaquil
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVICEURL=http://msvc-eureka
      - EUREKA_INSTANCE=msvc-eureka
      - DB_URL=jdbc:postgresql://192.168.0.46:5432/ErpEpmapaT
      - DB_USER=postgres
      - DB_PASS=3pmapaT24
      - HOST=http://192.168.0.165
      - MAIL_USERNAME=facturacion@epmapatulcan.gob.ec
      - MAIL_PASSWORD=79DB6F2BFA7FFED2E17F16CABA197D2063EB
      - MAIL_HOST=smtp.elasticemail.com
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://msvc-emails:9099/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-emails
networks:
  epmapat-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16







