version: "3.9"
services:
  config-server:
    build: config
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      - epmapat-nw
  msvc-eureka:
    build: eureka
    image: msvc-eureka:latest
    container_name: msvc-eureka
    ports:
      - "8761:8761"
    restart: always
  msvc-gateway:
    build: gateway
    image: msvc-gateway:latest
    container_name: msvc-gateway
    ports:
      - "9090:9090"
    restart: always
  msvc-recaudacion:
    build: recaudacion
    image: msvc-recaudacion:latest
    container_name: msvc-recaudacion
    ports:
      - "9092:9092"
    restart: always
    networks:
      - epmapat-nw
    depends_on:
      - msvc-eureka
networks:
  epmapat-nw:
    driver: bridge