version: "3.9"
services:
  config-server:
    build:
      context: config
      dockerfile: Dockerfile
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - config-server

  msvc-eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    image: msvc-eureka:latest
    container_name: msvc-eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-eureka
  msvc-gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    image: msvc-gateway:latest
    container_name: msvc-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-gateway
  msvc-login:
    build:
      context: login
      dockerfile: Dockerfile
    image: msvc-login:latest
    container_name: msvc-login
    ports:
      - "9091:9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-login
  msvc-recaudacion:
    build:
      context: recaudacion
      dockerfile: Dockerfile
    image: msvc-recaudacion:latest
    container_name: msvc-recaudacion
    ports:
      - "9092:9092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-recaudacion
  msvc-comercializacion:
    build:
      context: comercializacion
      dockerfile: Dockerfile
    image: msvc-comercializacion:latest
    container_name: msvc-comercializacion
    ports:
      - "9093:9093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-comercializacion
  msvc-pagosonline:
    build:
      context: pagosonline
      dockerfile: Dockerfile
    image: msvc-pagosonline:latest
    container_name: msvc-pagosonline
    ports:
      - "9094:9094"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.0.69:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-pagosonline
  msvc-sri:
    build:
      context: sri-files
      dockerfile: Dockerfile
    image: msvc-sri:latest
    container_name: msvc-sri
    ports:
      - "9096:9096"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka  # ✅ Usa el nombre del servicio Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msvc-eureka:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-sri
networks:
  epmapat-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16