version: "3.9"
services:
  config-server:
    build: config
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    restart: always
    networks:
      - epmapat-nw

  msvc-eureka:
    build: eureka
    image: msvc-eureka:latest
    container_name: msvc-eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=host.docker.internal
    restart: always
    networks:
      - epmapat-nw

  msvc-gateway:
    build: gateway
    image: msvc-gateway:latest
    container_name: msvc-gateway
    ports:
      - "9090:9090"
    environment:
      - EUREKA_HOSTNAME=host.docker.internal
    restart: always
    networks:
      - epmapat-nw
    depends_on:
      - config-server
      - msvc-eureka

  msvc-recaudacion:
    build: recaudacion
    image: msvc-recaudacion:latest
    container_name: msvc-recaudacion
    ports:
      - "9092:9092"
    environment:
      - EUREKA_HOSTNAME=host.docker.internal
    restart: always
    networks:
      - epmapat-nw
    depends_on:
      - msvc-eureka
      - config-server
  msvc-comercializacion:
    build: comercializacion
    image: msvc-comercializacion:latest
    container_name: msvc-comercializacion
    ports:
      - "9093:9093"
    restart: always
    networks:
      - epmapat-nw
    depends_on:
      - msvc-eureka
      - config-server
  msvc-pagosonline:
    build: pagosonline
    image: msvc-pagosonline:latest
    container_name: msvc-pagosonline
    ports:
      - "9094:9094"
    restart: always
    networks:
      - epmapat-nw
    depends_on:
      - msvc-eureka
      - config-server


networks:
  epmapat-nw:
    driver: bridge
############################################
version: "3.9"
services:
  config-server:
    build:
      context: config
      dockerfile: Dockerfile
    image: config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - config-server

  msvc-eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    image: msvc-eureka:latest
    container_name: msvc-eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://msvc-eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      epmapat-nw:
        aliases:
          - msvc-eureka

  # Other services follow same pattern with:
  # - Explicit build context
  # - Network aliases
  # - Health checks
  # - Proper Eureka configuration

networks:
  epmapat-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16