spring:
  application:
    name: msvc-contabilidad
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
server:
  port: 9102

eureka:
  instance:
    hostname: msvc-contabilidad
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICEURL}:8761/eureka/


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

