spring:
  application:
    name: msvc-gestiondocumental
  config:
    import: optional:configserver:http://192.168.0.69:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
