server:
  port: 9090

eureka:
  instance:
    hostname: msvc-gateway  # Nombre del servicio o contenedor de Gateway
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka estará disponible como msvc-eureka dentro de Docker Compose

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-recaudacion
          uri: http://localhost:9092
          predicates:
            - Path=/cajas/**|/facturas/**

        - id: msvc-comercializacion
          uri: http://localhost:9093
          predicates:
            - Path=/clientes/**|/abonados/**
