server:
  port: 8761
spring:
  application:
    name: msvc-eureka
eureka:
  instance:
    hostname: 192.168.100.16
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://192.168.100.16:${server.port}/eureka/