server:
  port: 8761
spring:
  application:
    name: msvc-eureka
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:host.docker.internal}  # Usar host.docker.internal para referirse al host desde dentro del contenedor
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://${EUREKA_HOSTNAME:host.docker.internal}:${server.port}/eureka/  # Uso de la variable EUREKA_HOSTNAME
