server:
  port: 9090
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: recaudacion
          uri: http://msvc-recaudacion:8090
          predicates:
            Path=/cajas/**