server:
  port: 9090
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-recaudacion
          uri: http://192.168.0.87:9092
          predicates:
            Path=/cajas/**