spring:
  application:
    name: msvc-gateway
  config:
    import: configserver:http://192.168.0.87:8880
  cloud:
    config:
      enabled: true
      uri: http://192.168.0.87:8880
      import-check:
        enabled: false