spring:
  application:
    name: msvc-gateway
  config:
    import: configserver:http://host.docker.internal:8888
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      import-check:
        enabled: false