spring:
  application:
    name: msvc-sri
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  mail:
    host: ${MAIL_HOST:smtp.elasticemail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.checkserveridentity: true
      mail.smtp.ssl.trust: ${MAIL_HOST:smtp.elasticemail.com}
      mail.smtp.connectiontimeout: 8000
      mail.smtp.timeout: 8000
      mail.smtp.writetimeout: 8000
      mail.debug: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
debug: false
xml:
  storage:
    path: /path/to/your/xml/storage
app:
  reports:
    path: /home/epmapaadmin/reportsEpmapat
  mail:
    from: facturacion@epmapatulcan.gob.ec
    # opcional:
    display-name: EPMAPA-T
    reply-to: facturacion@epmapatulcan.gob.ec
interes:
  tarea:
    cron: 0 */1 * * * *
sri:
  ambiente: 2 # 1=PRUEBAS, 2=PRODUCCIÓN
  polling:
    attempts: 40          # intentos máx
    initialSleepMs: 2000  # primera espera
    maxSleepMs: 8000      # techo de espera
    backoffFactor: 1.5    # factor de crecimiento
    stopOnNoAutorizado: true
  wsdl:
    local:
      recepcion: wsdl/RecepcionComprobantesOffline.wsdl
      autorizacion: wsdl/AutorizacionComprobantesOffline.wsdl
  endpoint:
    recepcion:
      pruebas: https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline
      produccion: https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline
    autorizacion:
      pruebas: https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline
      produccion: https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline
