spring:
  application:
    name: msvc-sri
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
debug: false
xml:
  storage:
    path: /path/to/your/xml/storage
app:
  reports:
    path: /home/epmapaadmin/reportsEpmapat