spring:
  application:
    name: msvc-eureka
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888  # URL of the Config Server


