spring:
  application:
    name: msvc-eureka
  config:
    import: configserver:http://192.168.100.16:8880
  cloud:
    config:
      enabled: true
      uri: http://192.168.100.16:8880
      import-check:
        enabled: false