spring:
  application:
    name: msvc-eureka
  config:
    import: configserver:http://config-server:8880
  cloud:
    config:
      enabled: true
      uri: http://config-server:8880
      import-check:
        enabled: false