spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:/config-data
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      fail-fast: false  # Evita fallos si el Config Server no responde
  profiles:
    active: default
