spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:/config-data
  cloud:
    config:
      enabled: true
      uri: http://config-service:8081
      fail-fast: true
  profiles:
    active: default
