spring:
  application:
    name: msvc-eureka
  cloud:
    config:
      enabled: true
      uri: http://config-service:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 5
  profiles:
    active: local  # Fallback profile

