spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:/config-data
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
  profiles:
    active: local
