spring:
  application:
    name: msvc-recaudacion
  config:
    import: optional:configserver:http://192.168.100.16:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.16:5432/ErpEpmapaT  # Usar el nombre del servicio de la base de datos en Docker
    username: postgres
    password: 086411421

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
