spring:
  application:
    name: msvc-recaudacion
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888  # Usar el nombre del servicio de Config Server
      import-check:
        enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ErpEpmapaT  # Usar el nombre del servicio de la base de datos en Docker
    username: postgres
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
