spring:
  application:
    name: msvc-recaudacion

  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      import-check:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ErpEpmapaT
    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none