spring:
  application:
    name: msvc-pagosonline
  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
app:
  api:
    base-url: "http://msvc-facturas:9092/api/rec/"
