spring:
  application:
    name: msvc-comercializacion
  config:
    import: optional:configserver:http://config-server:8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigura
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.16:5432/ErpEpmapaT  # Usar el nombre del servicio de la base de datos en Docker
    username: postgres
    password: 086411421

  jpa:
    database: POSTGRESQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
