spring:
  application:
    name: msvc-comercializacion
  config:
    import: optional:configserver:http://config-server:8888
  #autoconfigure:
  # exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfigura
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.69:5432/ErpEpmapaT  # Usar el nombre del servicio de la base de datos en Docker
    username: postgres
    password: Epmapat2025
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false #esto sirve para evitar el jsonignore
  jpa:
    database: POSTGRESQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size: 10MB
